import './globals.css';

export const metadata = {
  title: 'React App',
  description: 'Generated by create react app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">{children}</body>
    </html>
  );
}
